version: "3"

services:
    welegend-web:
        build:
            context: ../welegend
        container_name: welegend-web
        hostname: localhost
        networks:
            - proxy
        ports:
            - "3010:3000"
        environment:
            FORCE_COLOR: 1
            DEBUG_COLORS: "true"
            TERM: xterm-256color
            COLORTERM: truecolor
        labels:
            - traefik.enable=true
            - traefik.docker.network=proxy
            - traefik.http.routers.welegend.rule=Host(`welegend.mtech.id.vn`)
            - traefik.http.routers.welegend.entrypoints=websecure
            - traefik.http.routers.welegend.tls=true
            - traefik.http.routers.welegend.tls.certresolver=letsencrypt
            # - traefik.http.routers.personal-dashboard-https.middlewares=security-headers
        restart: unless-stopped

networks:
    proxy:
        external: true
